name: npl-2026a
channels:
  - conda-forge
dependencies:
  - folium
  - papermill
  - pytables
  - bottleneck
  - openssl
  - pyvista
  - ipympl
  - dask-geopandas
  - arm_pyart
  - celluloid
  - cmocean
  - pop-tools
  - h5py[build=*mpich*]
  - geocat-comp
  - cdsapi
  - jupyter-server-proxy
  - flox
  - matplotlib
  - tobac
  - f90nml
  - python-graphviz
  - pygraphviz
  - hvplot
  - python=3.13
  - geocat-viz
  - dask-labextension
  - h5netcdf
  - globus-cli
  - nc-time-axis
  - seawater
  - openpyxl
  - dask-jobqueue
  - scipy
  - libblas[build=*blis*]
  - boto3
  - intake-esgf
  - pynco
  - esmpy
  - numba
  - eccodes
  - cfgrib
  - widgetsnbextension
  - numexpr
  - scikit-image
  - intake
  - astropy
  - ca-certificates
  - docopt
  - ghp-import
  - numcodecs
  - datashader
  - ocgis
  - jupyter-book
  - numpy
  - dask
  - shapely
  - dask-mpi
  - cmcrameri
  - gempy
  - certifi
  - scikit-learn
  - wrf-python
  - intake-xarray
  - xgcm
  - pydap
  - pillow
  - xesmf
  - ipywidgets
  - pylint
  - django
  - seaborn
  - xrft
  - uxarray
  - xinvert
  - mpi4py
  - pyqt
  - pygrib
  - xwrf
  - awscli
  - gsw
  - click
  - fiona
  - pandas
  - statsmodels
  - python-wget
  - xarray
  - cartopy
  - gdal
  - regionmask
  - intake-esm
  - geoviews
  - netcdf4[build=*mpich*]
  - iris
  - descartes
  - jupyterlab
  - s3fs
  - lxml
  - ncar-jobqueue
  - contextily
  - pyhdf
  - cf-units
  - zarr
  - pywavelets
variables:
  UCX_TLS: tcp
prefix: /glade/u/apps/opt/miniforge/envs/npl-2026a
